author: Alex Vorsa
description: Vorsa ThoughtVault
keyword: hexo-theme, vuejs
favicon:

excerpt_link: (•••)

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: disqus

# disqus config


about:
  banner: /images/me.jpg
  avatar: /images/ar_hex.png
  description: What is my purpose?
  instagram_username: apollo.road
  vimeo_username: apolloroad

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
